1

In [1]:
symbols = "$*&!@"
codes = []

for symbol in symbols:
    codes.append(ord(symbol))

print(codes)

[36, 42, 38, 33, 64]


2

In [2]:
symbols = "$*&!@"

codes = [ord(symbol) for symbol in symbols]

print(codes)

[36, 42, 38, 33, 64]


3

In [3]:
x = '"!~$$*&!@'
dummy = [ord(x) for x in x]

print(x)
print(dummy)

"!~$$*&!@
[34, 33, 126, 36, 36, 42, 38, 33, 64]


4

In [4]:
symbols = '"!~$$*&!@'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 32]
print(beyond_ascii)

[34, 33, 126, 36, 36, 42, 38, 33, 64]


5

In [7]:
symbols = '"!~$$*&!@'
beyond_ascii = list(filter(lambda c: c > 64, map(ord, symbols)))

print(beyond_ascii, '\n')

print(f"Map function:\n>>> {map(ord, symbols)}")
print(f"List after map:\n>>> {list(map(ord, symbols))}")

[126] 

Map function:
>>> <map object at 0x7a7b23dfc490>
List after map:
>>> [34, 33, 126, 36, 36, 42, 38, 33, 64]


6

In [8]:
colors = ['black, white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]

print(tshirts)

for color in colors:
    for size in sizes:
        print((color, size))

[('black, white', 'S'), ('black, white', 'M'), ('black, white', 'L')]
('black, white', 'S')
('black, white', 'M')
('black, white', 'L')


7

In [12]:
symbols = "!#^&&#"
ord_s = tuple(ord(s) for s in symbols)

print(ord_s)

import array

ord_s = array.array('I', (ord(symbol) for symbol in symbols))

print(ord_s)

(33, 35, 94, 38, 38, 35)
array('I', [33, 35, 94, 38, 38, 35])


8

In [13]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
for tshirt in ('{} {}'.format(c, s) for c in colors for s in sizes):
    print(tshirt)

black S
black M
black L
white S
white M
white L


9

In [14]:
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'), ('ESP', 'XDA205856')]

for passport in sorted(traveler_ids):
    print('%s/%s' % passport)
    print('{}/{}'.format(passport[0], passport[1]))
    print(f'{passport[0]}/{passport[1]}')

BRA/CE342567
BRA/CE342567
BRA/CE342567
ESP/XDA205856
ESP/XDA205856
ESP/XDA205856
USA/31195855
USA/31195855
USA/31195855


10

In [15]:
for country, _ in traveler_ids:
    print(country)

USA
BRA
ESP


11

In [16]:
lax_corrdinates = (33.9425, -118.408056)
latitude, longitude = lax_corrdinates
print(latitude)
print(longitude)

33.9425
-118.408056


12

In [17]:
a=10; b=20
b, a = a, b
print(a, b)

20 10


13

In [19]:
print(divmod(20, 8))
t = (20, 8)
print(divmod(*t))
quotient, remainder = divmod(*t)
print(quotient, remainder)

(2, 4)
(2, 4)
2 4


14

In [20]:
import os
_, filename = os.path.split('/home/luciano/.ssh/idrsa.pub')
print(filename)

idrsa.pub


15

In [21]:
a, b, *rest = range(5)
print(a, b, rest)
a, b, *rest = range(3)
print(a, b, rest)
a, b, *rest = range(2)
print(a, b, rest)

0 1 [2, 3, 4]
0 1 [2]
0 1 []


16

In [22]:
a, *body, c, d = range(5)
print(a, body, c, d)
*head, b, c, d = range(5)
print(head, b, c, d)

0 [1, 2] 3 4
[0, 1] 2 3 4


17

In [23]:
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35, 139)),
    ('Delhi NCR', 'IN', 21, (28, 77)),
    ('Mexico City', 'MX', 20, (19, -99)),
    ('New York-Newark', 'US', 20, (40, -74)),
    ('Sao Paulo', 'BR', 19, (-23, -46))
]

print('{:15} | {:^9} | {:^9}'.format('', 'lat.', 'long.'))
fmt = '{:15} | {:9.4f} | {:9.4f}'

for name, cc, pop, (latitude, longitude) in metro_areas:
    if longitude <= 0:
        print(fmt.format(name, latitude, longitude))

                |   lat.    |   long.  
Mexico City     |   19.0000 |  -99.0000
New York-Newark |   40.0000 |  -74.0000
Sao Paulo       |  -23.0000 |  -46.0000


18

In [25]:
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689, 139.691))
print(tokyo)
print(tokyo.population)
print(tokyo.coordinates)
print(tokyo[1])

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689, 139.691))
36.933
(35.689, 139.691)
JP


19

In [27]:
print(City._fields)

LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613, 77.208))
delhi = City._make(delhi_data)
print(delhi._asdict())
for key, value in delhi._asdict().items():
    print(key + ':', value)

('name', 'country', 'population', 'coordinates')
{'name': 'Delhi NCR', 'country': 'IN', 'population': 21.935, 'coordinates': LatLong(lat=28.613, long=77.208)}
name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613, long=77.208)


20

In [29]:
l = [10, 20, 30, 40, 50, 60]
print(l[:2])
print(l[2:])
print(l[:3])
print(l[3:])

[10, 20]
[30, 40, 50, 60]
[10, 20, 30]
[40, 50, 60]


21

In [32]:
invoice = """
0.....6....................25........33.......40........
1909  Pimoroni              $17.50      3         $52.50
1489  6mm Tactile Switch    $4.95       2         $9.90
"""

SKU = slice(0, 6)
DESCRIPTION = slice(6, 25)
UNIT_PRICE = slice(25, 33)
QUANTITY = slice(33, 40)
ITEM_TOTAL = slice(55, None)

line_items = invoice.split('\n')[2:]
for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION])

   $17.5 Pimoroni           
   $4.95 6mm Tactile Switch 
 


22

In [34]:
l = list(range(10))
print(l)
l[2:5] = [20, 30]
print(l)
del l[5:7]
print(l)
l[3::2] = [11, 22]
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 20, 30, 5, 6, 7, 8, 9]
[0, 1, 20, 30, 5, 8, 9]
[0, 1, 20, 11, 5, 22, 9]


23

In [35]:
l[2:5] = 100

TypeError: can only assign an iterable

24

In [36]:
l[2:5] = [100]
print(l)

[0, 1, 100, 22, 9]


25

In [38]:
l = [1, 2, 3]
print(l * 5)
print(5 * 'abcd')

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
abcdabcdabcdabcdabcd


26

In [39]:
board = [['_'] * 3 for i in range(3)]
print(board)
board[1][2] = 'X'
print(board)

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]


27

In [40]:
weird_board = [['_'] * 3] * 3
print(weird_board)
weird_board[1][2] = 'O'
print(weird_board)

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', 'O'], ['_', '_', 'O'], ['_', '_', 'O']]


28

In [42]:
row = ['_'] * 3
board = []
for i in range(3):
    board.append(row)

board[1][2] = 'X'
print(board)

[['_', '_', 'X'], ['_', '_', 'X'], ['_', '_', 'X']]


29

In [45]:
board = []
for i in range(3):
    row = ['_'] * 3
    board.append(row)

print(board)

board[2][0] = 'X'
print(board)

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]


30

In [46]:
l = [1, 2, 3]
print(id(l))
l *= 2
print(l)
print(id(l))

134668512390080
[1, 2, 3, 1, 2, 3]
134668512390080


31

In [48]:
t = (1, 2, 3)
print(id(t))
t *= 2
print(id(t))

134668513665920
134668513632096


32

In [52]:
t = (1, 2, [30, 40])
print(t)
t[2] += [50, 60]
#답: t는 (1, 2, [30, 40, 50, 60])이 되며 TypeError도 같이 발생

(1, 2, [30, 40])


TypeError: 'tuple' object does not support item assignment

33

In [53]:
print(t)

(1, 2, [30, 40, 50, 60])


34

In [54]:
fruits = ['grape', 'raspberry', 'apple', 'banana']
print(sorted(fruits))
print(fruits)
print(sorted(fruits, reverse=True))
print(sorted(fruits, key=len))


['apple', 'banana', 'grape', 'raspberry']
['grape', 'raspberry', 'apple', 'banana']
['raspberry', 'grape', 'banana', 'apple']
['grape', 'apple', 'banana', 'raspberry']


35

In [55]:
print(sorted(fruits, key=len, reverse=True))
print(fruits)
fruits.sort()
print(fruits)

['raspberry', 'banana', 'grape', 'apple']
['grape', 'raspberry', 'apple', 'banana']
['apple', 'banana', 'grape', 'raspberry']


36

In [56]:
from array import array
from random import random

floats = array('d', (random() for i in range(10**7)))
print(floats[-1])

0.12131786566040603


37

In [57]:
with open('floats.bin', 'wb') as f:
    floats.tofile(f)

floats2 = array('d')
with open('floats.bin', 'rb') as f:
    floats2.fromfile(f, 10**7)

print(floats2[-1])
print(floats2 == floats)

0.12131786566040603
True


38

In [58]:
import array

numbers = array.array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
print(len(memv))
print(memv[0])
memv_oct = memv.cast('B')
print(memv_oct.tolist())
memv_oct[5] = 4
print(numbers)

5
-2
[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]
array('h', [-2, -1, 1024, 1, 2])


39

In [59]:
import numpy
a = numpy.arange(12)
print(a)
print(type(a))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>


40

In [60]:
print(type(a))
print(a.shape)
a.shape = 3, 4
print(a)

<class 'numpy.ndarray'>
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


41

In [62]:
print(a[2])
print(a[2, 1])
print(a[:, 1])

[ 8  9 10 11]
9
[1 5 9]


42

In [63]:
print(a.transpose())

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


43

In [64]:
from collections import deque
dq = deque(range(10), maxlen=10)
print(dq)
dq.rotate(3)
print(dq)
dq.rotate(-4)
print(dq)

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)
deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], maxlen=10)


44

In [65]:
dq.appendleft(-1)
print(dq)
dq.extend([11, 22, 33])
print(dq)
dq.extendleft([10, 20, 30, 40])
print(dq)

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33], maxlen=10)
deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8], maxlen=10)
